name: Build and Deploy
on:
  push:
    branches: [v3]
  pull_request:
    branches: [v3]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and build
        run: |
          npm ci
          cp dist/index.html dist/404.html
          npx vite build --base=/anistats/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
